name = input("enter your name: ")
surname = input("enter your surname: ")
age = input("enter your age: ")
num1 = input("enter the first number: ")
num2 = input("enter the second number: ")
print(type(name))
print(type(surname))
print(type(age))
print(type(num1))
print(type(num2))